# Project: Project1
# Makefile created by Red Panda C++ 3.4.3279

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-Wl,--stack,12582912"
INCS     = 
CXXINCS  = 
CXXFLAGS = $(CXXINCS) "-g3" "-fno-ms-extensions" "-pipe" "-Wall" "-Werror=return-type" "-Werror=vla" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-fno-ms-extensions" "-pipe" "-Wall" "-Werror=implicit-int" "-Werror=return-type" "-Werror=vla" "-D_DEBUG"
NASM_FLAGS   =  "-f" "elf64" "-g"
WINDRESFLAGS = 
OBJ      = main.o student.o person.o
BIN      = Project1.exe
LINKOBJ  = "main.o" "student.o" "person.o"
CLEANOBJ = "main.o" "student.o" "person.o" "Project1.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

Project1.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "Project1.exe" $(LIBS)

main.o: main.cpp person.h student.h route.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

student.o: student.cpp person.h student.h
	$(CXX) -c "student.cpp" -o "student.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

person.o: person.cpp person.h
	$(CXX) -c "person.cpp" -o "person.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk
